#ifndef ROBOT_BUILD_CONFIG_H
#define ROBOT_BUILD_CONFIG_H

/* Shared by the STM32 target and future NUC/Linux targets. */
#define ROBOT_PLATFORM_STM32 1
#define ROBOT_PLATFORM_NUC   0

#define ROBOT_HAS_PLUGIN_GRAPH 1
#define ROBOT_USE_PLUGIN_GRAPH 0

#define ROBOT_BASE_RATE_HZ 1000U
#define ROBOT_MAX_PLUGIN_NODES 32U
#define ROBOT_MAX_PLUGIN_EDGES 64U

#define ROBOT_ENABLE_PERF_COUNTERS 1
#define ROBOT_ENABLE_PERF_TRACE    0
#define ROBOT_ENABLE_DEBUG_SNAPSHOT 1

#endif /* ROBOT_BUILD_CONFIG_H */
